In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/ameenamekkrakunnan/preprocessing-csv/T124OPPE1_Preprocessing5.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("/kaggle/input/datasets/ameenamekkrakunnan/preprocessing-csv/T124OPPE1_Preprocessing5.csv")

In [4]:
data.head()

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO

### no of samples

In [6]:
data.shape

(4000, 14)

### Average price of house

In [8]:
data["PRICE"].mean()

np.float64(24.52924464570181)

### no of houses having greater than 5 rooms

In [13]:
data.query("RM >= 5")

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.888632,0.635426,18.327980,1.214383,7.0,100.0,3.268107,25,667.377709,21.213656,397.210534,21.537646,13.966395,NO
3996,1.485618,81.724553,5.754772,0.422434,8.0,29.0,5.300785,5,245.586194,20.083284,398.517120,3.603526,37.343527,NO
3997,1.515471,55.774211,4.055462,0.854897,7.0,29.0,7.274133,5,371.170011,18.166783,389.254112,5.526206,32.048290,NO
3998,1.213408,0.434945,8.364137,1.312692,6.0,87.0,4.874288,4,307.242745,22.455347,304.039084,16.896982,14.958820,NO
3999,0.208430,36.479194,6.629429,1.324817,6.0,29.0,8.640236,3,305.434860,17.848331,395.517130,12.591712,18.459617,NO

In [14]:
data.query("RM >= 5").shape

(3925, 14)

In [15]:
data[data["RM"] >= 5]

,CRIM,ZN,INDUS,POLINDEX,RM,AGE,DIS,HIGHWAYCOUNT,TAX,PTRATIO,IMM,BPL,PRICE,RIVERSIDE
0,0.339451,80.271980,2.166533,0.484391,8.0,20.0,11.355250,6,336.729137,22.540915,376.060450,6.969427,21.669087,NO
1,1.059730,1.909323,10.590647,0.755596,7.0,53.0,5.238639,5,277.033814,19.479797,395.990102,12.433205,26.237995,NO
2,1.307746,45.833665,4.222120,2.362586,8.0,41.0,4.776458,7,398.069607,15.228967,397.233472,6.777399,36.525943,NO
3,0.478246,0.433153,10.679947,1.458648,7.0,73.0,2.605083,9,432.777976,19.465542,339.411533,16.772050,21.628186,NO
4,9.141458,1.142936,19.280459,0.813295,8.0,99.0,3.117690,24,666.592484,22.056939,304.230845,19.517317,13.399126,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,9.888632,0.635426,18.327980,1.214383,7.0,100.0,3.268107,25,667.377709,21.213656,397.210534,21.537646,13.966395,NO
3996,1.485618,81.724553,5.754772,0.422434,8.0,29.0,5.300785,5,245.586194,20.083284,398.517120,3.603526,37.343527,NO
3997,1.515471,55.774211,4.055462,0.854897,7.0,29.0,7.274133,5,371.170011,18.166783,389.254112,5.526206,32.048290,NO
3998,1.213408,0.434945,8.364137,1.312692,6.0,87.0,4.874288,4,307.242745,22.455347,304.039084,16.896982,14.958820,NO
3999,0.208430,36.479194,6.629429,1.324817,6.0,29.0,8.640236,3,305.434860,17.848331,395.517130,12.591712,18.459617,NO

In [16]:
data[data["RM"] >= 5].shape

(3925, 14)

### average price of top 10 most expensive houses

In [19]:
data["PRICE"].nlargest(10).mean()

np.float64(52.2033351761825)

### unknown values

In [20]:
data["RM"].isna().sum()

np.int64(0)

In [21]:
data[data["RM"]==-1].shape

(68, 14)

In [22]:
data["RM"].describe()

count    4000.000000
mean        6.992000
std         1.398186
min        -1.000000
25%         6.000000
50%         7.000000
75%         8.000000
max        11.000000
Name: RM, dtype: float64

### total missing or unknown values in the RIVERSIDE feature

In [23]:
data["RIVERSIDE"].describe()

count     4000
unique       3
top         NO
freq      3628
Name: RIVERSIDE, dtype: object

In [26]:
data["RIVERSIDE"].value_counts()

RIVERSIDE
NO         3628
YES         284
UNKNOWN      88
Name: count, dtype: int64

### how many houses are on riverside and were built within last 50 years

In [27]:
data[
    (0 <= data['AGE']) &
    (data['AGE'] <= 50) &
    (data['RIVERSIDE'] == 'YES')
].shape

(37, 14)

### how many houses are near to exactly 6,7, or 8 highways(all threee inclusive)

In [28]:
data[data['HIGHWAYCOUNT'].isin([6, 7, 8])].shape

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

(1209, 14)

In [30]:
data[
    (data['HIGHWAYCOUNT'] == 6) |
    (data['HIGHWAYCOUNT'] == 7) |
    (data['HIGHWAYCOUNT'] == 8)
].shape

(1209, 14)

### Create a column 'CATEGORY' and divide the houses in categories a following
* 1. house price < 10 lacs
  2. 10 <= house price < 20lacs
  3. 20 <= house price < 30 lacs
  4. 30 <= house price < 40lacs
  5. house price >- 40lacs

### which category has the highest no of records

In [31]:
bins=[-float('inf'),10,20,30,40,float('inf')]
labels=['c1','c2','c3','c4','c5']
data['CATEGORY']=pd.cut(data['PRICE'],bins=bins,labels=labels,right=False)
data['CATEGORY'].value_counts().idxmax()

'c3'